<a href="https://colab.research.google.com/github/JoyAssis/womakerscode_dataAnalitics_exercicios1/blob/main/Numpy_WMC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.

In [2]:
import numpy as np

In [ ]:
np.random.random((4,3))

array([[0.83350629, 0.31602918, 0.36805748],
       [0.84474502, 0.17330137, 0.11993589],
       [0.3252084 , 0.87370367, 0.83364576],
       [0.54381752, 0.13754391, 0.58901718]])

2. Crie um array com valores inteiros, 3 linhas e 5 colunas com valores
aleatórios.

In [ ]:
np.random.randint(20,size=(3,5))

array([[ 5, 12, 12, 15,  8],
       [ 4,  3, 10, 16, 18],
       [11, 13,  5, 10,  6]])

3. Crie um array com 5 colunas e 10 linhas inicializados com zeros.

In [ ]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4. Crie um array que vá entre 0 e 90 pulando de 4 em 4.

In [ ]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

5. Reduza o array (5,7) a apenas uma dimensão.

In [8]:
arr = np.random.random((5,7))

In [9]:
print(arr)

[[0.29806982 0.41241313 0.84032919 0.85425314 0.21236569 0.05439858
  0.10891901]
 [0.69808028 0.3178481  0.47102782 0.18697631 0.98945665 0.4905844
  0.65411064]
 [0.96848007 0.44941283 0.06235507 0.67247197 0.62246301 0.16754248
  0.56675545]
 [0.72181522 0.32845321 0.49075663 0.47416746 0.95832643 0.35975553
  0.7314534 ]
 [0.83307242 0.66148936 0.85881768 0.61896792 0.30918183 0.87193066
  0.81903261]]


In [10]:
arr_one_dimension = arr.flatten()

In [11]:
print(arr_one_dimension)

[0.29806982 0.41241313 0.84032919 0.85425314 0.21236569 0.05439858
 0.10891901 0.69808028 0.3178481  0.47102782 0.18697631 0.98945665
 0.4905844  0.65411064 0.96848007 0.44941283 0.06235507 0.67247197
 0.62246301 0.16754248 0.56675545 0.72181522 0.32845321 0.49075663
 0.47416746 0.95832643 0.35975553 0.7314534  0.83307242 0.66148936
 0.85881768 0.61896792 0.30918183 0.87193066 0.81903261]


6. Considerando que você é uma organizadora de um jogo de bingo. Crie
um array que irá representar a cartilha desses jogos de bingo. os
números das suas cartelas variam entre 1 e 30, e você terá 10
participantes. Cada cartela terá 12 números (4, 3). Crie um array que
representa esse jogo.

In [14]:
cartilhas = np.random.randint(1,31, size=(10, 4,3))
print(cartilhas)

[[[19 23 25]
  [ 3 13 14]
  [ 8 25  2]
  [21 19 15]]

 [[20 16 29]
  [ 9 20 29]
  [11 25 19]
  [ 3 13 14]]

 [[25 13  7]
  [14 19  2]
  [29 26  5]
  [23  1 25]]

 [[ 1  5  1]
  [17 14 20]
  [18 26 16]
  [26 30 22]]

 [[ 8 28  8]
  [ 5 28 21]
  [19 11  3]
  [14 10  1]]

 [[ 5 11  6]
  [27  9 14]
  [ 7  7 25]
  [ 7  1  2]]

 [[18  5  4]
  [25 14 24]
  [24 13 23]
  [19  5 13]]

 [[ 4 25 27]
  [ 6 23  6]
  [22 12  7]
  [13 13 29]]

 [[11 12 30]
  [21 13  8]
  [ 7 30 23]
  [22 29 30]]

 [[ 3 23 29]
  [ 9 13 26]
  [ 7 28 13]
  [29 11  8]]]


7. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e
6 colunas.

In [15]:
metade_cartilhas = cartilhas.reshape(5,4,6)

In [16]:
print(metade_cartilhas)

[[[19 23 25  3 13 14]
  [ 8 25  2 21 19 15]
  [20 16 29  9 20 29]
  [11 25 19  3 13 14]]

 [[25 13  7 14 19  2]
  [29 26  5 23  1 25]
  [ 1  5  1 17 14 20]
  [18 26 16 26 30 22]]

 [[ 8 28  8  5 28 21]
  [19 11  3 14 10  1]
  [ 5 11  6 27  9 14]
  [ 7  7 25  7  1  2]]

 [[18  5  4 25 14 24]
  [24 13 23 19  5 13]
  [ 4 25 27  6 23  6]
  [22 12  7 13 13 29]]

 [[11 12 30 21 13  8]
  [ 7 30 23 22 29 30]
  [ 3 23 29  9 13 26]
  [ 7 28 13 29 11  8]]]


# Manipulando Arrays

1.

In [17]:
especies=np.array([[747,89,33,5],[623,123,32,13],[501,22,49,2],[116,101,42,10],[297,56,69,22],[613,64,27,7],[295,84,29,14],[692,105,72,16],[229,103,35,5],[374,124,70,1]])